debug: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.hyunbenny.mybox: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybox
    username: myboxUser
    password: myboxUser1234

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false # OSIV
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100

#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 10MB
#      max-file-size: 1024MB
#      max-request-size: 1024MB

  sql:
    init:
      mode: always
#  data:
#    rest:
#      base-path: /api
#      detection-strategy: annotated

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-southeast-2
    stack:
      auto: false

application:
  bucket:
    name: hyunbenny-mybox